### PR TITLE
Refactor/tests/code coverage

### PR DESCRIPTION
**Pull request by SimonLXiong**
Final Code Coverage push. This is 86% Code Coverage and excludes Save, Save As, and Exit functionality. (As per suggestion by Jimmy and because it just won't work or track on the code.)

### CODE REVIEW

**Review by anthonyOrth — APPROVED** [review]
Awesome job Simon you rock!

**Review by Delinquent-Pointer — APPROVED** [review]
🛑Did you test the exit function?

**Review by ulises-aguilar — APPROVED** [review]
Looks good.

**Review by rudmad13 — APPROVED** [review]
Looks good to me

**Pull request merged**
