### PR TITLE
Zoom in and out, moving canvas, unlimited space

### PR DESCRIPTION
**Pull request by Delinquent-Pointer**

### CODE REVIEW

**Comment by Delinquent-Pointer** [comment]
image

**Review by ulises-aguilar — APPROVED** [review]
Looks good.

**Review by rudmad13 — APPROVED** [review]
Looks kosher

**Review by SimonLXiong — APPROVED** [review]
Looks good. pass it through.

**Review by anthonyOrth — APPROVED** [review]
looks good to me

**Pull request merged**
