### PR TITLE
This wasn't a bug in the code, this was a path issue should not have relative path for mvn build

### PR DESCRIPTION
**Pull request by Delinquent-Pointer**

### CODE REVIEW

**Comment by Delinquent-Pointer** [comment]
CommandRegistries commandRegistries = CommandRegistries.getInstance("CLICommands.json"); this is exsample all file parsing must be in class, all method calls only require file name all none java file should be in resources under mvn

**Review by ulises-aguilar — APPROVED** [review]
Looks good.

**Review by anthonyOrth — APPROVED** [review]
looks good to me.

**Review by rudmad13 — APPROVED** [review]
This is insanely KOSHER!!!!!

**Review by SimonLXiong — APPROVED** [review]
Fine to me

**Pull request merged**
