### PR TITLE
java doc for the project.

### PR DESCRIPTION
**Pull request by anthonyOrth**
take a look at it and tell me if you want me to change anything.

### CODE REVIEW

**Review by ulises-aguilar — APPROVED** [review]
Good job, looks kosher to me.
Need google format.

**Review by Delinquent-Pointer — CHANGES_REQUESTED** [review]
Spotless failure

**Review by ulises-aguilar — CHANGES_REQUESTED** [review]
Google format

**Review by SimonLXiong — APPROVED** [review]
All of this is approved and ready to go.

**Review by rudmad13 — APPROVED** [review]
Looks good to me

**Review by ulises-aguilar — APPROVED** [review]
Looks good.

**Pull request merged**
