### PR TITLE
changes to README for CLI and Testing sections

### PR DESCRIPTION
**Pull request by anthonyOrth**
here ya all go!

### CODE REVIEW

**Review by Delinquent-Pointer — CHANGES_REQUESTED** [review]
Line 160 - 162 (make this section clearer and more professional) Also Tag This section for contributors/developers
To access the current code coverage for the project, which is essential for writing effective tests, follow these steps:

Navigate to GitHub and open the project repository.

Go to the Actions tab.

Code coverage details are available under every action event as artifacts. This makes it easy to stay informed about the current state of the code.

By using this tool, developers can ensure high-quality code and write effective tests.

**Comment by anthonyOrth** [comment]
updated

**Review by Delinquent-Pointer — APPROVED** [review]
www.github.com user is already on GitHub rest is much better. "Do it yourself" vibe check is here

**Review by SimonLXiong — APPROVED** [review]
Looks good

**Review by ulises-aguilar — APPROVED** [review]
Looks good.

**Comment by anthonyOrth** [comment]
update again lol

**Review by rudmad13 — APPROVED** [review]
This work is insanely good !!!!!

**Pull request merged**
